### PR TITLE
Fix broken @seealso links in roxygen2 documentation

### LINKED ISSUE #1100: Many broken `@seealso` links throughout
Broken ex: https://epiforecasts.io/EpiNow2/reference/summary.epinow.html#see-also
Working ex: https://epiforecasts.io/EpiNow2/reference/epinow.html#see-also

Broken links occur because `@seealso` requires a function link like `[function_name()])`
https://github.com/search?q=repo%3Aepiforecasts%2FEpiNow2+%22%40seealso%22&type=code

### PR DESCRIPTION
**Pull request by seabbs**
**This is entirely from an agent so do not review until I have pinged for review as I will do a first pass**

## Summary
This PR fixes 14 broken `@seealso` references across 8 R files by converting plain text function references to proper roxygen2 link syntax `[function_name()]`. This ensures documentation hyperlinks work correctly on the pkgdown site.

## Changes
- Fixed non-existent `rt_settings` reference to `rt_opts()` (R/create.R:173)
- Added proper brackets and parentheses to all function references in `@seealso` tags
- Split long multi-function references across lines to respect 80-character limit
- Removed trailing text from malformed reference in R/report.R:138

## Files Modified
- R/create.R (2 fixes)
- R/epinow-internal.R (1 fix)
- R/estimate_secondary.R (2 fixes)
- R/estimate_truncation.R (1 fix)
- R/opts.R (1 fix)
- R/plot.R (2 fixes)
- R/report.R (1 fix)
- R/summarise.R (5 fixes)
- All corresponding .Rd files in man/

## Testing
- Documentation regenerated successfully with `devtools::document()`
- All references now use proper roxygen2 markdown syntax
- No new warnings or errors introduced

Fixes #1100

## Summary by CodeRabbit

* **Documentation**
  * Improved cross-references and linking throughout help documentation to enhance navigation between related functions and provide better resource discoverability.

### CODE REVIEW

File: R/estimate_secondary.R [hunk 1]
```diff
@@ -367,7 +367,7 @@ update_secondary_args <- function(data, priors, verbose = TRUE) {
 #'
 #' @return A `ggplot` object.
 #'
-#' @seealso plot estimate_secondary
+#' @seealso [plot.estimate_secondary()] [estimate_secondary()]
```
Comment (seabbs) [inline R/estimate_secondary.R]:
```suggestion
#' @seealso [estimate_secondary()]
```

File: R/estimate_truncation.R [hunk 2]
```diff
@@ -286,7 +286,7 @@ estimate_truncation <- function(data,
 #' @param ... Pass additional arguments to plot function. Not currently in use.
 #'
 #' @return `ggplot2` object
-#' @seealso plot estimate_truncation
+#' @seealso [plot.estimate_truncation()] [estimate_truncation()]
```
Comment (seabbs) [inline R/estimate_truncation.R]:
```suggestion
#' @seealso [estimate_truncation()]
```

File: R/plot.R [hunk 3]
```diff
@@ -377,7 +377,8 @@ plot_summary <- function(summary_results,
 #' @param ... Pass additional arguments to report_plots
 #' @importFrom rlang arg_match
 #'
-#' @seealso plot report_plots estimate_infections
+#' @seealso [plot.estimate_infections()] [report_plots()]
```
Comment (seabbs) [inline R/plot.R]:
```suggestion
#' @seealso [report_plots()] [estimate_infections()]
```

File: R/plot.R [hunk 4]
```diff
@@ -377,7 +377,8 @@ plot_summary <- function(summary_results,
...
+#' [estimate_infections()]
```
Comment (seabbs) [inline R/plot.R]:
```suggestion
```

**Review by sbfnk — APPROVED** [review]
