### PR TITLE
Fix broken breakpoint feature

### LINKED ISSUE #1092: breakpoint feature is overestimating cases
See new figure in the rendered vignette in #1085.

### PR DESCRIPTION
**Pull request by jamesmbaazam**
## Description

This PR closes #1092. 

## Initial submission checklist

- [x] My PR is based on a package issue and I have explicitly linked it.
- [x] I have tested my changes locally (using `devtools::test()` and `devtools::check()`).
- [ ] I have added or updated unit tests where necessary.
- [ ] I have updated the documentation if required and rebuilt docs if yes (using `devtools::document()`).
- [ ] I have followed the established coding standards (and checked using `lintr::lint_package()`).
- [x] I have added a news item linked to this PR.

## After the initial Pull Request 

- [ ] I have reviewed Checks for this PR and addressed any issues as far as I am able.

### CODE REVIEW

File: tests/testthat/test-preprocessing.R [hunk 1]
```diff
@@ -68,3 +68,52 @@ test_that("add_horizon doesn't try to identify non-equally spaced gaps", {
...
+    date = as.Date("2020-01-01") + 0:2,
+    confirm = 1:3
+  )
+  expect_error(
+    add_breakpoints(data, dates = as.Date("2020-01-10")),
+    "Breakpoint date.*not found in data"
+  )
+})
+
+test_that("add_breakpoints works with no dates supplied (no-op)", {
```
Comment (jamesmbaazam) [inline tests/testthat/test-preprocessing.R]:
```suggestion
test_that("add_breakpoints works with no dates supplied", {
```

**Review by seabbs — APPROVED** [review]
Looks good to close this out we need a test of pad_reported_cases I think

**Comment by jamesmbaazam** [comment]
> Looks good to close this out we need a test of pad_reported_cases I think

I've added tests for `pad_reported_cases()` in b56f5f6de1cb25656aed9547d41b309789fdf638.
