### PR TITLE
fix final period estimation when shifting cases

### LINKED ISSUE #948: non-mechanistic model doesn't connect final fit correcly
Looking at #695 I noticed that there's a bit of a discontinuity in the non-mechanistic model (or whatever we may want to call it), see also e.g. the vignette plot (not super clear but visible in the infections plot):

https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections_options-nonparametric-1.png

I think this is because there's an issue with how the data is extrapolated to fill future dates in
https://github.com/epiforecasts/EpiNow2/blob/6c6d90c9527e677c4a12797077b9b36d460cfa6d/R/create.R#L122

### PR DESCRIPTION
**Pull request by sbfnk**
## Description

This PR closes #948 and adds a regression test.

## Initial submission checklist

- [X] My PR is based on a package issue and I have explicitly linked it.
- [X] I have tested my changes locally (using `devtools::test()` and `devtools::check()`).
- [X] I have added or updated unit tests where necessary.
- [X] I have updated the documentation if required and rebuilt docs if yes (using `devtools::document()`).
- [X] I have followed the established coding standards (and checked using `lintr::lint_package()`).
- [X] I have added a news item linked to this PR.

## After the initial Pull Request 

- [x] I have reviewed Checks for this PR and addressed any issues as far as I am able.

### CODE REVIEW

**Comment by seabbs** [comment]
(no biggy but some more PR info like what is done at a high level would be useful at least for me)

File: R/create.R [hunk 1]
```diff
@@ -109,34 +110,26 @@ create_shifted_cases <- function(data, shift,
   ]
 
   ## Forecast trend on reported cases using the last week of data
-  final_period <- data.table::data.table(
-    confirm =
-      shifted_reported_cases[!is.na(confirm)][
-        max(1, .N - smoothing_window):.N
-      ]$confirm
-  )[,
+  final_period <- shifted_reported_cases[!is.na(confirm)][
```
Comment (seabbs) [inline R/create.R:113]: In the spirit of recent changes there is quite a good arg this should move inside the model

Comment (seabbs) [reply R/create.R:113]: as it has always been a big hack

File: R/create.R [hunk 2]
```diff
@@ -109,34 +110,26 @@ create_shifted_cases <- function(data, shift,
...
-  ][
-    ,
-    t := t - (.N - horizon - shift - 6)
-  ][
-    ,
+    date >= min(final_period$date), t := seq_len(.N)
+  ][,
     confirm := data.table::fifelse(
-      t >= 7,
+      !is.na(t) & t >= 0,
```
Comment (seabbs) [inline R/create.R:124]: I think this is the key change. If so makes sense to me.

**Review by seabbs — APPROVED** [review]

File: R/create.R [hunk 3]
```diff
@@ -109,34 +110,26 @@ create_shifted_cases <- function(data, shift,
...
   ## Estimate unreported future infections using a log linear model
   shifted_reported_cases <- shifted_reported_cases[
-    ,
-    t := seq_len(.N)
-  ][
-    ,
-    t := t - (.N - horizon - shift - 6)
-  ][
-    ,
+    date >= min(final_period$date), t := seq_len(.N)
```
Comment (seabbs) [inline R/create.R:121]: I think this is the key change and if so all makes sense to me.

File: R/create.R (hunk 1 above)
Comment (sbfnk) [reply R/create.R:113]: yes good point
